### ISSUE TITLE
साहायता करने हेतु आगे आना

### ISSUE THREAD

**Issue by goyalyashpal** [NyxTrail/aksharam#3]
नमस्कार!

इस app के लिए, और उसपर भी इसे f-droid पर डालने हेतु आपका बहुत बहुत धन्यवाद। 

* किसी नई लिपि/भाषा को जोड़ने में आपकी साहायता कैसे करें?
* क्या आपने कोई contribution guidelines डालने कि सोची हैं?

**Comment by NyxTrail** [comment]
Hello @yashpalgoyal1304 

Thanks for trying out my app.

Sorry I have to answer you in English. I am not that confident with my Hindi skills.

I haven't yet thought about how to accept contributions here.

Regarding addition of support for more scripts:
- The data files for the scripts are kept here: [aksharam-data](https://github.com/NyxTrail/aksharam-data)
- To add a new script we need to:
  1. Add a new json file with appropriate definitions for that script. This file includes each letter of the script along with corresponding character for every other script. (This file is for those who want to learn the new script.)
  2. Add corresponding characters of the new script to every other language data file. (This is for those who already know the new script, but want to use it for learning another script.)
  3. Steps 1 and 2, are decoupled. The app should work fine if only either step one or two is done. But, ideally we should do both.

**Comment by NyxTrail** [comment]
Answered.

**Comment by goyalyashpal** [comment]
क्षमा करें, मैं कहीं व्यस्त हो गया हूँ ...

आप प्रतीक्षा न करें

**Comment by NyxTrail** [comment]
Hey,
Sorry about the ping. I was just testing out how I should close this issue.
